site_name: Solawi Stadt, Land, Beides
# site_url:

theme:
  name: material
  palette:
    - scheme: slate # default
      default: true
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      
nav: 
  - Wilkommen: index.md
  - Einführung: einfuehrung.md
  - Für Mitglieder: 
    - Mitgliedschaft anlegen: fuer_mitglieder/mitgliedschaft_anlegen.md
    - Test: fuer_mitglieder/test.md

plugins: 
  - search
