name: ci 
on:
  push:
    branches:
      - main
      - master
      - poetry-ci
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry install --no-root
      - run: poetry run mkdocs gh-deploy --force
